### ISSUE TITLE
Required version of setuptools

### ISSUE THREAD

**Issue by psykzz** [pyupio/pyup#192]
Running `pyup --repo=****/***** --user-token=******* --initial`

```
Traceback (most recent call last):
  File "/usr/bin/pyup", line 7, in <module>
    from pyup.cli import main
  File "/usr/lib/python2.7/site-packages/pyup/cli.py", line 3, in <module>
    from pyup.bot import DryBot, Bot
  File "/usr/lib/python2.7/site-packages/pyup/bot.py", line 5, in <module>
    from .requirements import RequirementsBundle
  File "/usr/lib/python2.7/site-packages/pyup/requirements.py", line 4, in <module>
    from pkg_resources._vendor.packaging.specifiers import SpecifierSet
```

Was able to fix the error by installing an older version of setuptools (it isn't defined in your setup.py)

**Comment by jayfk** [comment]
Best case would be to use the `packaging` library as a lot of other things depend on setuptools to be pinned on a particular release.

**Comment by coagulant** [comment]
Probably have to pin setuptools/packaging version somewhere, does not work with latest versions installed by default

```
(tmp-8d8c8e5949807b8c) ➜  pyup git:(master) ✗ python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'34.0.2'
>>> import packaging
>>> packaging.__version__
'16.8'
>>> from pkg_resources._vendor.packaging.specifiers import SpecifierSet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pkg_resources._vendor'
```

**Comment by jayfk** [comment]
Yeah, it's horrible. I've pinned it to `setuptools<=26.1.1` for now.
