### ISSUE TITLE
Contributing workflow is broken

### ISSUE THREAD

**Issue by coagulant** [pyupio/pyup#194]
Hey, @jayfk! I like pyup idea and want to use pyup. Here are problems that blocked my progress to making any pull requests, because not being able to have a green tests:

1) Tox build is broken with error `Could not detect requirement name, please specify one with #egg=` (hashin is not installed)
https://travis-ci.org/pyupio/pyup/jobs/195612487#L219

2) `python setup.py test` fails under python <3.5: `AttributeError: 'module' object has no attribute 'test_bot'`

```
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    tests_require=test_requirements,
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/prophet/work/forks/pyup/.tox/py34/lib/python3.4/site-packages/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "/Users/prophet/work/forks/pyup/.tox/py34/lib/python3.4/site-packages/setuptools/command/test.py", line 234, in run_tests
    **exit_kwarg
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/prophet/work/forks/pyup/.tox/py34/lib/python3.4/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_bot'
```

3) Setuptools internal import does not work with latest setuptools  #192

**Comment by jayfk** [comment]
All of this is fixed now, check out the `0.6.0` release.
