### ISSUE TITLE
Pyup not taking the default set branch in Github

### ISSUE THREAD

**Issue by audiolion** [pyupio/pyup#199]
Private repository (private access enabled obviously). I pushed a new branch 'develop' to my repository and changed it to be the default. I closed a pull request and deleted the branch, however the new PR was still against the old 'master' branch (which is no longer default and has been set to be a protected branch). I have tried removing the repository from pyup.io and re-adding it and I still got the same behavior.

I had to add a `.pyup.yml` file with `branch = develop` to get the correct behavior but the docs state that pyup makes PR's against the default branch on the repository (usually master)

**Comment by jayfk** [comment]
Thanks for reporting that @audiolion.

Could you send me a mail with the repo name to support@pyup.io so I can check the logs what exactly happened there?

**Comment by achaussier** [comment]
Hello,

FYI, this also occurs with public repositories.

**Comment by DEKHTIARJonathan** [comment]
I have the exact same bug with this repository: https://github.com/DEKHTIARJonathan/FeedCrunch.IO

**Comment by DEKHTIARJonathan** [comment]
Any news @jayfk on this ?

**Comment by jayfk** [comment]
Still debugging this. I've pushed a fix about two weeks ago that fixed most of the problems related to this bug. Could be a server side thing.

**Comment by DEKHTIARJonathan** [comment]
Humm ... Do you think if I delete my repository on pyup and re-add it it could change smthg ?

**Comment by jayfk** [comment]
Yup, it's worth a try.

**Comment by DEKHTIARJonathan** [comment]
Something is wrong with this repository... Still making PR to Master: https://github.com/DEKHTIARJonathan/FeedCrunch.IO/pull/40

**Comment by jayfk** [comment]
Looks like the bot fails to parse the config file :/
```
celeryworker_1  | [2017-09-07 20:02:16,427: INFO/ForkPoolWorker-18686] Running update for repo DEKHTIARJonathan/FeedCrunch.IO
celeryworker_1  | [2017-09-07 20:02:16,434: INFO/ForkPoolWorker-18687] Running update for repo erikdab/pyrelaxmapper
celeryworker_1  | [2017-09-07 20:02:16,478: INFO/ForkPoolWorker-18684] Adding requirement file at test_requirements.txt
celeryworker_1  | [2017-09-07 20:02:16,478: INFO/ForkPoolWorker-18684] Getting file at test_requirements.txt for branch master
celeryworker_1  | [2017-09-07 20:02:16,863: INFO/ForkPoolWorker-18686] Getting file at /.pyup.yml for branch master
celeryworker_1  | [2017-09-07 20:02:16,911: INFO/ForkPoolWorker-18687] Getting file at /.pyup.yml for branch master
celeryworker_1  | [2017-09-07 20:02:17,274: WARNING/ForkPoolWorker-18686] Unable to parse config file /.pyup.yml
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/src/pyup/pyup/bot.py", line 78, in get_repo_config
celeryworker_1  |     return yaml.safe_load(content)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
celeryworker_1  |     return load(stream, SafeLoader)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
celeryworker_1  |     return loader.get_single_data()
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
celeryworker_1  |     node = self.get_single_node()
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
celeryworker_1  |     document = self.compose_document()
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
celeryworker_1  |     node = self.compose_node(None, None)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
celeryworker_1  |     node = self.compose_mapping_node(anchor)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
celeryworker_1  |     item_value = self.compose_node(node, item_key)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
celeryworker_1  |     node = self.compose_sequence_node(anchor)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 110, in compose_sequence_node
celeryworker_1  |     while not self.check_event(SequenceEndEvent):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
celeryworker_1  |     self.current_event = self.state()
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
celeryworker_1  |     "expected <block end>, but found %r" % token.id, token.start_mark)
celeryworker_1  | yaml.parser.ParserError: while parsing a block collection
celeryworker_1  |   in "<unicode string>", line 33, column 3:
celeryworker_1  |       - requirements.txt
celeryworker_1  |       ^
celeryworker_1  | expected <block end>, but found '<block mapping start>'
celeryworker_1  |   in "<unicode string>", line 35, column 7:
celeryworker_1  |           update: all
celeryworker_1  |
```

**Comment by DEKHTIARJonathan** [comment]
Problem solved !
Thanks again

**Comment by Azulinho** [comment]
similar problem here, I had to create a master branch with only the .pyup.yml file.
