### ISSUE TITLE
KeyError: 'pip._vendor.urllib3.contrib' Python3.6 pip 9.0.2

### ISSUE THREAD

**Issue by bluespider42** [pyupio/pyup#285]
Just to let you know that pyup is affected by this issue:
https://github.com/pypa/pip/issues/5079
I'm running the bot in a docker container based off python3.6-stretch.
```
Traceback (most recent call last):
  File "/usr/local/bin/pyup", line 7, in <module>
    from pyup.cli import main
  File "/usr/local/lib/python3.6/site-packages/pyup/cli.py", line 3, in <module>
    from pyup.bot import Bot
  File "/usr/local/lib/python3.6/site-packages/pyup/bot.py", line 5, in <module>
    from .requirements import RequirementsBundle
  File "/usr/local/lib/python3.6/site-packages/pyup/requirements.py", line 11, in <module>
    import hashin
  File "/usr/local/lib/python3.6/site-packages/hashin.py", line 16, in <module>
    import pip
  File "/usr/local/lib/python3.6/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```

**Comment by bluespider42** [comment]
Upgrading pip solves this
