### ISSUE TITLE
pyup bot fails `AttributeError: module 'dparse.filetypes' has no attribute 'setup_cfg'`

### ISSUE THREAD

**Issue by bluespider42** [pyupio/pyup#288]
On running pyup bot (with and without a .pyup.yml)
Provider: gitlab.com
```
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\venv\Scripts\pyup.exe\__main__.py", line 9, in <module>
  File "...\venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "...\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "...\venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "...\venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "...\venv\lib\site-packages\pyup\cli.py", line 45, in main
    bot.update(branch=branch, initial=initial)
  File "...\venv\lib\site-packages\pyup\bot.py", line 118, in update
    self.get_all_requirements()
  File "...\venv\lib\site-packages\pyup\bot.py", line 503, in get_all_requirements
    self.add_requirement_file(path, sha)
  File "...\venv\lib\site-packages\pyup\bot.py", line 518, in add_requirement_file
    for other_file in req_file.other_files:
  File "...\venv\lib\site-packages\pyup\requirements.py", line 125, in other_files
    self._parse()
  File "...\venv\lib\site-packages\pyup\requirements.py", line 167, in _parse
    self._parse_setup_cfg()
  File "...\venv\lib\site-packages\pyup\requirements.py", line 153, in _parse_setup_cfg
    self.parse_dependencies(filetypes.setup_cfg)
AttributeError: module 'dparse.filetypes' has no attribute 'setup_cfg'
```

**Comment by bluespider42** [comment]
I made some modifications to .pyup.yml and now it's the same as #287 (my requirements.txt is also in a subfolder)

**Comment by jayfk** [comment]
What is the output of `pip freeze | grep dparse`?

**Comment by rafaelpivato** [comment]
If you are still experiencing this, please update your **pyupio** and **dparse** packages accordingly, and report back with `--log DEBUG` option.
