### ISSUE TITLE
Asking for  branch that does not exist gives a traceback

### ISSUE THREAD

**Issue by tibs** [pyupio/pyup#306]
Using pyup (version 1.01 within pipenv, running on Mac OS/X 10.13.4 High Sierra) if I do:
```
$ pyup --repo=tibs/redis-talk  --user-token=$USER_TOKEN  --branch no-such-branch
```
then I get a traceback, from which it is not entirely obvious that the problem is choosing a branch that does not exist.

```
Traceback (most recent call last):
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/bin/pyup", line 11, in <module>
    sys.exit(main())
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/pyup/cli.py", line 45, in main
    bot.update(branch=branch, initial=initial)
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/pyup/bot.py", line 122, in update
    self.get_all_requirements()
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/pyup/bot.py", line 491, in get_all_requirements
    for file_type, path in self.iter_git_tree(sha=sha):
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/pyup/providers/github.py", line 64, in iter_git_tree
    for item in repo.get_git_tree(branch, recursive=True).tree:
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/github/Repository.py", line 1735, in get_git_tree
    parameters=url_parameters
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/github/Requester.py", line 185, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Users/tonibb01/.local/share/virtualenvs/pyup-55eKFErJ/lib/python3.6/site-packages/github/Requester.py", line 198, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/git/trees/#get-a-tree'}
```

**Comment by rafaelpivato** [comment]
:+1: We need better error handling indeed.
