### ISSUE TITLE
PyGithub get_emails now returns a named tuple

### ISSUE THREAD

**Issue by DamianZaremba** [pyupio/pyup#409]
Since https://github.com/PyGithub/PyGithub/pull/1890 `get_emails` is now a named tuple rather than a dict which is causing

```
Traceback (most recent call last):
  File "/tmp/bin/pyup", line 8, in <module>
    sys.exit(main())
  File "/tmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/tmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/lib/python3.9/site-packages/pyup/cli.py", line 50, in main
    bot.update(branch=branch, initial=initial)
  File "/tmp/lib/python3.9/site-packages/pyup/bot.py", line 123, in update
    self.apply_updates(
  File "/tmp/lib/python3.9/site-packages/pyup/bot.py", line 197, in apply_updates
    pull_request = self.commit_and_pull(
  File "/tmp/lib/python3.9/site-packages/pyup/bot.py", line 420, in commit_and_pull
    new_sha = self.provider.create_commit(
  File "/tmp/lib/python3.9/site-packages/pyup/providers/github.py", line 167, in create_commit
    extra_kwargs["committer"] = self.get_committer_data(committer)
  File "/tmp/lib/python3.9/site-packages/pyup/providers/github.py", line 195, in get_committer_data
    if item["primary"]:
TypeError: tuple indices must be integers or slices, not str
```

Pinning PyGithub to `1.54.0.1` enables `pyup` to function as expected.

**Comment by yeisonvargasf** [comment]
Thanks for the report, it will be handled in the next version.
