### ISSUE TITLE
AssertionError: none

### ISSUE THREAD

**Issue by oliverweinm** [pyupio/pyup#417]
After installing pyup via pip and trying it out, I keep getting this AssertionError which is confusing as isinstance(base_url, str) shouldn't return None in this case.
Does anybody know why it comes to that and/or how to fix this? Both the repo String and the user-token String are valid, I double checked that already.

Thanks in advance guys

pyup --repo=oliverweinm/MCBDD2022 --user-token=<REDACTED_HERE> --initial
Traceback (most recent call last):
  File "/usr/local/bin/pyup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyup/cli.py", line 50, in main
    bot.update(branch=branch, initial=initial)
  File "/usr/local/lib/python3.9/site-packages/pyup/bot.py", line 121, in update
    self.configure(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyup/bot.py", line 106, in configure
    repo=self.user_repo,
  File "/usr/local/lib/python3.9/site-packages/pyup/bot.py", line 38, in user_repo
    self._user_repo = self.provider.get_repo(token=self.user_token, name=self.repo_name)
  File "/usr/local/lib/python3.9/site-packages/pyup/providers/github.py", line 40, in get_repo
    return self._api(token).get_repo(name)
  File "/usr/local/lib/python3.9/site-packages/pyup/providers/github.py", line 32, in _api
    self.__api = Github(self.__token, base_url=self.url, timeout=50, verify=verify)
  File "/usr/local/lib/python3.9/site-packages/github/MainClass.py", line 123, in __init__
    assert isinstance(base_url, str), base_url
AssertionError: None

**Comment by yeisonvargasf** [comment]
Hi, It should be fixed If you pass `--provider_url https://api.github.com` and `--branch your_default_branch`.

It's a bug and it will be fixed in the next PyUp version.
